title:        imagegradientrectangle
name:         imagegradientrectangle
description:  imagegradientrectangle is a function that will draw a gradient filled rectangle on your PHP GD images.
author:       Andrew G. Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://imagegradientrectangle.agjgd.org"
includes_dir: .
layouts_dir:  documentation/imagegradientrectangle.agjgd.org/layouts
exclude:      [
               .github,
               .github/*.md,
               .github/*.yml,
               .github/CODEOWNERS,
               .github/ISSUE_TEMPLATE,
               .github/ISSUE_TEMPLATE/*.yml,
               CHANGELOG.md,
               CNAME,
               composer.json,
               documentation/README.md,
               examples/*.php,
               examples/*.ttf,
               LICENSE,
               README.md,
               source
              ]
